CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `accounthaveonepaymenter` AS select distinct `accountowners`.`AccountNumber` AS `accountnumber` from `accountowners` where (`NUMOFPAYMENTACCESS`(`accountowners`.`AccountNumber`) = 1);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `customersignedatleastone` AS select distinct `customer`.`FirstName` AS `FirstName`,`customer`.`LastName` AS `LastName` from (`signers` join `customer` on((`customer`.`ID` = `signers`.`IDS`)));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `moresigneraccess` AS select distinct `accountowners`.`AccountNumber` AS `accountNumber` from `accountowners` where (`NUMOFSIGNERACCESS`(`accountowners`.`AccountNumber`) > `NUMOFREQUIERDSIGNS`(`accountowners`.`AccountNumber`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `moresigners` AS select distinct `paymentorder`.`SourceAccount` AS `SourceAccount` from `paymentorder` where (`numOfSigns`(`paymentorder`.`SourceAccount`) > `NUMOFREQUIERDSIGNS`(`paymentorder`.`SourceAccount`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `onesigneraccessforsignpayment` AS select `paymentorder`.`IDP` AS `IDP`,`paymentorder`.`NCCreator` AS `NCCreator`,`paymentorder`.`FullPrice` AS `FullPrice`,`paymentorder`.`SourceAccount` AS `SourceAccount`,`paymentorder`.`IDPaymentVerifier` AS `IDPaymentVerifier`,`paymentorder`.`NoteOfCreator` AS `NoteOfCreator` from `paymentorder` where (`NumOfSignerAccess`(`paymentorder`.`SourceAccount`) = 1);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `onlyonesignatureforpay` AS select `paymentorder`.`IDP` AS `IDP`,`paymentorder`.`NCCreator` AS `NCCreator`,`paymentorder`.`FullPrice` AS `FullPrice`,`paymentorder`.`SourceAccount` AS `SourceAccount`,`paymentorder`.`IDPaymentVerifier` AS `IDPaymentVerifier`,`paymentorder`.`NoteOfCreator` AS `NoteOfCreator` from `paymentorder` where `paymentorder`.`SourceAccount` in (select `accounthaveonepaymenter`.`accountnumber` from `accounthaveonepaymenter`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `orderpaymentsthatcreatorcantsign` AS select `paymentorder`.`IDP` AS `IDP`,`paymentorder`.`NCCreator` AS `NCCreator`,`paymentorder`.`FullPrice` AS `FullPrice`,`paymentorder`.`SourceAccount` AS `SourceAccount`,`paymentorder`.`IDPaymentVerifier` AS `IDPaymentVerifier`,`paymentorder`.`NoteOfCreator` AS `NoteOfCreator` from `paymentorder` where (`paymentorder`.`SourceAccount`,(select `customer`.`ID` from `customer` where (`customer`.`NationalCode` = `paymentorder`.`NCCreator`))) in (select `accountowners`.`AccountNumber`,`accountowners`.`IDAO` from `accountowners` where ((`accountowners`.`SignatureAccess` = FALSE) and (`accountowners`.`PaymentAccess` = TRUE)));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `readytopayed` AS select `paymentorder`.`IDP` AS `IDP`,`paymentorder`.`NCCreator` AS `NCCreator`,`paymentorder`.`FullPrice` AS `FullPrice`,`paymentorder`.`SourceAccount` AS `SourceAccount`,`paymentorder`.`IDPaymentVerifier` AS `IDPaymentVerifier`,`paymentorder`.`NoteOfCreator` AS `NoteOfCreator` from `paymentorder` where ((`numOfSigns`(`paymentorder`.`IDP`) >= `NumOfRequierdSigns`(`paymentorder`.`SourceAccount`)) and isnull(`paymentorder`.`IDPaymentVerifier`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `transactionthatcreatercantsign` AS select `orderpaymentsthatcreatorcantsign`.`IDP` AS `IDP`,`orderpaymentsthatcreatorcantsign`.`NCCreator` AS `NCCreator`,`orderpaymentsthatcreatorcantsign`.`FullPrice` AS `FullPrice`,`orderpaymentsthatcreatorcantsign`.`SourceAccount` AS `SourceAccount`,`orderpaymentsthatcreatorcantsign`.`IDPaymentVerifier` AS `IDPaymentVerifier`,`orderpaymentsthatcreatorcantsign`.`NoteOfCreator` AS `NoteOfCreator`,`transaction`.`DestAccountNumber` AS `DestAccountNumber`,`transaction`.`Price` AS `Price` from (`orderpaymentsthatcreatorcantsign` join `transaction` on((`orderpaymentsthatcreatorcantsign`.`IDP` = `transaction`.`IDP`)));
